/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./viewer/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2d3133",
        "on-primary-fixed": "#001a41",
        "tertiary-fixed-dim": "#c3c6cd",
        "surface-bright": "#f8f9fb",
        "on-secondary-container": "#00742e",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#e0e2e9",
        "on-secondary-fixed": "#002108",
        "background": "#f8f9fb",
        "secondary-fixed": "#94f99f",
        "on-primary": "#ffffff",
        "on-primary-container": "#ecefff",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed": "#181c21",
        "surface-container-highest": "#e0e3e5",
        "surface-dim": "#d8dadc",
        "inverse-primary": "#adc6ff",
        "on-primary-fixed-variant": "#004493",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#43474d",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-container": "#edf0f7",
        "primary": "#006e2b",
        "secondary-fixed-dim": "#78dc86",
        "tertiary": "#51555a",
        "primary-fixed-dim": "#adc6ff",
        "outline": "#727785",
        "on-surface-variant": "#424753",
        "surface": "#f8f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e0e3e5",
        "primary-container": "#94f99f",
        "surface-tint": "#005bc0",
        "primary-fixed": "#d8e2ff",
        "tertiary-container": "#696d73",
        "surface-container": "#eceef0",
        "on-tertiary": "#ffffff",
        "on-surface": "#191c1e",
        "on-error": "#ffffff",
        "secondary-container": "#0969da",
        "secondary": "#0051ae",
        "on-secondary-fixed-variant": "#00531e",
        "outline-variant": "#c2c6d6",
        "on-background": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xs": "4px",
        "gutter": "16px",
        "lg": "24px",
        "sm": "8px",
        "base": "4px",
        "margin-page": "40px",
        "md": "16px",
        "xl": "32px"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "headline-md": ["Inter"],
        "label-md": ["Work Sans"],
        "body-lg": ["Inter"],
        "code-sm": ["ui-monospace"],
        "headline-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "body-sm": ["Inter"]
      },
      fontSize: {
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-md": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "code-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}],
        "headline-sm": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-sm": ["13px", {"lineHeight": "18px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
