/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./viewer/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2d3133",
        "on-primary-fixed": "#001a41",
        "tertiary-fixed-dim": "#c3c6cd",
        "surface-bright": "#f8f9fb",
        "on-secondary-container": "#00742e",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#e0e2e9",
        "on-secondary-fixed": "#002108",
        background: "#f8fafc",
        "secondary-fixed": "#94f99f",
        "on-primary": "#ffffff",
        "on-primary-container": "#ecefff",
        "surface-container-low": "#f1f5f9",
        "on-tertiary-fixed": "#181c21",
        "surface-container-highest": "#e2e8f0",
        "surface-dim": "#cbd5e1",
        "inverse-primary": "#adc6ff",
        "on-primary-fixed-variant": "#004493",
        error: "#dc2626",
        "on-tertiary-fixed-variant": "#43474d",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-container": "#edf0f7",
        primary: "#006e2b",
        "secondary-fixed-dim": "#78dc86",
        tertiary: "#64748b",
        "primary-fixed-dim": "#adc6ff",
        outline: "#94a3b8",
        "on-surface-variant": "#475569",
        surface: "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#f1f5f9",
        "primary-container": "#dcfce7",
        "surface-tint": "#006e2b",
        "primary-fixed": "#d8e2ff",
        "tertiary-container": "#696d73",
        "surface-container": "#f8fafc",
        "on-tertiary": "#ffffff",
        "on-surface": "#0f172a",
        "on-error": "#ffffff",
        "secondary-container": "#0969da",
        secondary: "#0284c7",
        "on-secondary-fixed-variant": "#00531e",
        "outline-variant": "#e2e8f0",
        "on-background": "#0f172a",
        "surface-container-high": "#e2e8f0",
        "on-error-container": "#991b1b",
      },
      boxShadow: {
        subtle: "0 1px 3px 0 rgb(0 0 0 / 0.05), 0 1px 2px -1px rgb(0 0 0 / 0.05)",
        card: "0 4px 6px -1px rgb(0 0 0 / 0.04), 0 2px 4px -2px rgb(0 0 0 / 0.03)",
        glass: "0 8px 32px 0 rgba(31, 38, 135, 0.07)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        gutter: "16px",
        lg: "24px",
        sm: "8px",
        base: "4px",
        "margin-page": "40px",
        md: "16px",
        xl: "32px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-md": ["Work Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "code-sm": ["ui-monospace", "monospace"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
};

